name: ci

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  check-clean:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Bender
        run: |
          rustup update stable --no-self-update && rustup default stable
          if ! $(which bender); then
            cargo install bender --version 0.25.3
          fi
      - name: Check clean make targets
        run: |
          make -B prepare_sim gen_ci gen_regs
          make clean
          git status && test -z "$(git status --porcelain)"
  check-stale:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Bender
        run: |
          rustup update stable --no-self-update && rustup default stable
          if ! $(which bender); then
            cargo install bender --version 0.25.3
          fi
      - name: Check clean makefile
        run: |
          make -B prepare_sim gen_ci gen_regs
          git status && test -z "$(git status --porcelain)"
  lint:
    runs-on: ubuntu-latest
    needs: [check-clean, check-stale]
    steps:
      - uses: actions/checkout@v2
      - name: Python Requirements
        run: python3 -m pip install -r requirements.txt
      - name: Lint commits
        run: python3 util/lint-commits.py HEAD
      - name: Lint license
        run: scripts/check-license
      - name: Lint verilog
        run: scripts/verible-lint
      - name: Lint python
        run: scripts/python-lint
