# Copyright 2022 ETH Zurich and University of Bologna.
# Solderpad Hardware License, Version 0.51, see LICENSE for details.
# SPDX-License-Identifier: SHL-0.51

# Author: Michael Rogenmoser <michaero@iis.ee.ethz.ch>

name: ci

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  check-clean:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.9'
          cache: 'pip'
      - name: Install Bender
        run: make bender
      - name: Python Requirements
        run: pip install -r requirements.txt
      - name: Check clean make targets
        run: |
          make -B prepare_sim gen_ci gen_regs
          make clean
          git status && test -z "$(git status --porcelain)"
        env:
          BENDER: ./bender
  check-stale:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.9'
          cache: 'pip'
      - name: Install Bender
        run: make bender
      - name: Python Requirements
        run: pip install -r requirements.txt
      - name: Check clean makefile
        run: |
          make -B prepare_sim gen_ci gen_regs
          git status && test -z "$(git status --porcelain)"
        env:
          BENDER: ./bender
  lint:
    runs-on: ubuntu-latest
    needs: [check-clean, check-stale]
    strategy:
      fail-fast: false
      matrix: 
        lint_check: ['python3 util/lint-commits.py HEAD', 'scripts/check-license', 'scripts/verible-lint', 'scripts/python-lint']
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.9'
          cache: 'pip'
      - name: Python Requirements
        run: python3 -m pip install -r requirements.txt
      - name: Install Bender
        run: make bender
      - name: Lint commits
        run: ${{ matrix.lint_check }}
        env:
          BENDER: ./bender
